library(hashmap)

dict <- hashmap("", "")
dict[["redovna profesorka"]] <- "redovni profesor"
dict[["redovni profesor"]] <- "redovni profesor"
dict[["vanredna profesorka"]] <- "vanredni profesor"
dict[["vanredni profesor"]] <- "vanredni profesor"
dict[["honorarna profesorka"]] <- "vanredni profesor"
dict[["honorarni profesor"]] <- "vanredni profesor"
dict[["docent"]] <- "docent"
dict[["docentkinja"]] <- "docent"
dict[["docent u penziji"]] <- "docent u penziji"
dict[["docentkinja u penziji"]] <- "docent u penziji"
dict[["asistent"]] <- "asistent"
dict[["asistentkinja"]] <- "asistent"
dict[["nastavnica stranog jezika"]] <- "nastavnik stranog jezika"
dict[["nastavnik stranog jezika"]] <- "nastavnik stranog jezika"
dict[["viši nastavnik stranog jezika"]] <- "viši nastavnik stranog jezika"
dict[["nastavnik jezika"]] <- "nastavnik stranog jezika"
dict[["nastavnica jezika"]] <- "nastavnik stranog jezika"
dict[["nastavnica španskog jezika"]] <- "nastavnik stranog jezika"
dict[["saradnik u nastavi"]] <- "saradnik u nastavi"
dict[["saradnica u nastavi"]] <- "saradnik u nastavi"
dict[["viša naučna saradnica"]] <- "viši naučni saradnik"
dict[["viši naučni saradnik"]] <- "viši naučni saradnik"
dict[["naučna saradnica"]] <- "naučni saradnik"
dict[["naučni saradnik"]] <- "naučni saradnik"
dict[["istraživač"]] <- "istraživač"
dict[["istraživačica"]] <- "istraživač"
dict[["naučna istraživačica"]] <- "istraživač"
dict[["istraživačica-saradnik"]] <- "istraživač-saradnik"
dict[["istraživač-saradnik"]] <- "istraživač-saradnik"
dict[["istraživačica-saradnica"]] <- "istraživač-saradnik"
dict[["istraživačica – saradnica"]] <- "istraživač-saradnik"
dict[["istraživačica saradnica"]] <- "istraživač-saradnik"
dict[["istraživačica saradnik"]] <- "istraživač-saradnik"
dict[["istraživač saradnik"]] <- "istraživač-saradnik"
dict[["istraživač saradnik u penziji"]] <- "istraživač-saradnik u penziji"
dict[["naučna savetnica"]] <- "naučni savetnik"
dict[["naučni savetnik"]] <- "naučni savetnik"
dict[["profesor emeritus"]] <- "profesor emeritus"
dict[["profesorka emeritus"]] <- "profesor emeritus"
dict[["profesorka emerita"]] <- "profesor emeritus"
dict[["profesor emerita"]] <- "profesor emeritus"
dict[["redovni profesor u penziji"]] <- "redovni profesor u penziji"
dict[["redovna profesorka u penziji"]] <- "redovni profesor u penziji"
dict[["vanredni profesor u penziji"]] <- "vanredni profesor u penziji"
dict[["vanredna profesorka u penziji"]] <- "vanredni profesor u penziji"
dict[["profesor u penziji"]] <- "profesor u penziji"
dict[["profesorka u penziji"]] <- "profesor u penziji"
dict[["stručna saradnica"]] <- "stručni saradnik"
dict[["stručni saradnik"]] <- "stručni saradnik"
dict[["viša stručna saradnica"]] <- "stručni saradnik"
dict[["viši stručni saradnik"]] <- "stručni saradnik"
dict[["istraživač-pripravnik"]] <- "istraživač-pripravnik"
dict[["istraživačica-pripravnik"]] <- "istraživač-pripravnik"
dict[["istraživačica-pripravnica"]] <- "istraživač-pripravnik"
dict[["istraživač pripravnik"]] <- "istraživač-pripravnik"
dict[["istraživačica pripravnik"]] <- "istraživač-pripravnik"
dict[["istraživačica pripravnica"]] <- "istraživač-pripravnik"
dict[["nastavnica veština u penziji"]] <- "nastavnik veština u penziji"
dict[["nastavnik veština u penziji"]] <- "nastavnik veština u penziji"
dict[["nastavnica veština"]] <- "nastavnik veština"
dict[["nastavnik veština"]] <- "nastavnik veština"
dict[["predavač"]] <- "predavač"
dict[["predavačica"]] <- "predavač"
dict[["viši predavač"]] <- "viši predavač"
dict[["viša predavačica"]] <- "viši predavač"
dict[["pukovnik predavač u penziji"]] <- "pukovnik predavač u penziji"
dict[["samostalni stručni saradnik"]] <- "samostalni stručni saradnik"
dict[["klinički asistent"]] <- "klinički asistent"
dict[["viši lektor"]] <- "viši lektor"
dict[["viši lektor u penziji"]] <- "viši lektor u penziji"
dict[["viša lektorka"]] <- "viši lektor"
dict[["lektor"]] <- "lektor"
dict[["lektorka"]] <- "lektor"
dict[["demonstrator"]] <- "demonstrator"
dict[["demonstratorka"]] <- "demonstrator"
dict[["dopisni član SANU"]] <- "dopisni član SANU"
dict[["redovni član SANU"]] <- "redovni član SANU"
dict[["asistent u penziji"]] <- "asistent u penziji"
dict[["profesor"]] <- "profesor"
dict[["profesorka"]] <- "profesor"
dict[["naučni savetnik u penziji"]] <- "naučni savetnik u penziji"
dict[["naučna savetnica u penziji"]] <- "naučni savetnik u penziji"
dict[["naučni saradnik u penziji"]] <- "naučni saradnik u penziji"
dict[["naučna saradnica u penziji"]] <- "naučni saradnik u penziji"
dict[["viši naučni saradnik u penziji"]] <- "viši naučni saradnik u penziji"
dict[["viša naučna saradnica u penziji"]] <- "viši naučni saradnik u penziji"
dict[["profesor strukovnih studija"]] <- "profesor strukovnih studija"
dict[["profesorka strukovnih studija"]] <- "profesor strukovnih studija"
dict[["gost profesor"]] <- "gost profesor"
dict[["viši umetnički saradnik"]] <- "viši umetnički saradnik"
dict[["viša umetnička saradnica"]] <- "viši umetnički saradnik"
dict[["umetnički saradnik"]] <- "umetnički saradnik"
dict[["umetnička saradnica"]] <- "umetnički saradnik"
dict[["samostalni umetnički saradnik"]] <- "samostalni umetnički saradnik"
dict[["samostalna umetnička saradnica"]] <- "samostalni umetnički saradnik"